name: Maestro
on: [push]

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Pods dependencies
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

      - name: Install npm dependencies
        run: yarn install

      - name: Install iOS dependencies
        run: npx pod-install

      - name: Install ios-deploy
        run: npm install -g ios-deploy

      - uses: futureware-tech/simulator-action@v2
        with:
          model: "iPhone 14"

      - name: Run app on simulator
        run: npx react-native run-ios

      - uses: dniHze/maestro-test-action@v1
        with:
          flow: maestro/smoke-test.yml
          report: report.xml

      - uses: actions/upload-artifact@v3
        with:
          name: maestro-report
          path: ./report.xml
